device:
  name_contains: "wr4800_8210"
  host_api_contains: "WDM-KS"
  minimum_input_channels: 0
  minimum_output_channels: 2

stream:
  sample_rate: 48000
  input_channels: 0
  output_channels: 2
  block_size: 128
  dtype: "float32"