device:
  name_contains: "Analogue 1 + 2 (Focusrite USB Audio)"
  minimum_input_channels: 2
  minimum_output_channels: 0

stream:
  sample_rate: 48000
  input_channels: 2
  output_channels: 2
  block_size: null
  dtype: float32