device:
  name_contains: "wc4800_8210"
  host_api_contains: "WDM-KS"
  minimum_input_channels: 2
  minimum_output_channels: 0

stream:
  sample_rate: 48000
  input_channels: 2
  output_channels: 0
  block_size: 128
  dtype: "float32"